"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "easy-peasy";
import { store } from "./store/store";
import { RouteChangeListener } from "./hooks/useRouteChangeListener";
import MyNavBar from "./components/MyNavBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import PageTransition from "./components/PageTransition";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <head>{/* <Script src="http://localhost:8097"></Script> */}</head>
      <body className={inter.className}>
        <PageTransition>
          <StoreProvider store={store}>
            <ToastContainer
              position="top-right"
              autoClose={500}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
            <MyNavBar />
            <RouteChangeListener />
            {children}
          </StoreProvider>
        </PageTransition>
      </body>
    </html>
  );
}
